"use strict";
let stringVar = "text";
let intVar = 3;
let isVisible = true;
let anyVar = "123";
console.log(stringVar);
console.log(intVar);
console.log(isVisible);
console.log(anyVar);
let intArray = [1, 3, 4, 5, 2];
let stringArray = ["try", "to", "catch", "me",];
